import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'
import Header from "./components/Layout/header";
import Providers from "./providers";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const author = localFont({
  src: "./Author-Variable.woff2",
  variable: "--font-author",
});


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body className={`${author.variable} font-author antialiased`} >
            <Providers>
              <Header />
              <main className="mt-14">
              {children}
              </main>
            </Providers>
          </body>
    </html>
  );
}
